on: [push]

name: AzureARMDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create Storage Account
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name StorageAccountDeployment \
            --resource-group test25 \
            --template-file .github/workflows/armtemplates/storageaccount.json \
            --parameters storageAccountType=Standard_GRS

      - name: Create Fileshare #EkspermimentellSone
        uses: azure/CLI@v1
        with:
          inlineScript: |
           az storage share-rm create \
           --resource-group test25 \
           --storage-account test25stdsa \
           --name automatisk \
           --quota 5120 \
           --enabled-protocols SMB \
           --output none
